# Generated by Django 5.1.1 on 2024-11-21 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='fanlar')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name="o'quvchilar")),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(77)], verbose_name='yosh')),
                ('adress', models.CharField(blank=True, max_length=70, null=True, verbose_name='manzil')),
                ('subjects', models.ManyToManyField(related_name='students', to='edu.subjects', verbose_name='qaysi fanda oqishi')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='oquvchi bahosi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.students', verbose_name='oquvchilar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.subjects', verbose_name='qaysi fanga olgani')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='oqituvchi ismi')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='edu.subjects', verbose_name="o'qituvchi qaysi fanda oqitishi")),
            ],
        ),
    ]
